name: youtube_captioned_player
description: "Improved without iframe YouTube player with subtitles using video_player and youtube_explode_dart."
version: 0.0.5
repository: https://github.com/emrhnzngn/youtube_captioned_player
issue_tracker: https://github.com/emrhnzngn/youtube_captioned_player/issues
homepage: https://github.com/emrhnzngn/youtube_captioned_player

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  youtube_explode_dart: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
